[package]
name = "ctk"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
aws-config = "1.1"
aws-sdk-sts = "1.1"
tokio = { version = "1", features = ["full"] }
